# Site settings
title: Cloud2
email: getmore@cloud2.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Prototype for Cloud2 website
baseurl: ""
url: "https://www.cloud2.co.uk"
phone: "07800 100100"
twitter_id: Cloud2Ltd
linkedin: cloud2-ltd
googleplus: "102289998183049121834"
theme-path: theme-assets # path to header assets etc
map-api-key: AIzaSyB3U7uwIvCyq01orxppAIC1v73y-FBGygY
sass:
  sass_dir: _sass
  style: compressed

collections:
  solution:
    output: true
    permalink: /solution/:path/
  case:
    output: true
    permalink: /case-studies/:path/
  event:
    output: true
    permalink: /events/:path/
  partner:
    output: true
    permalink: /partners/:path/
  profile:
    output: true
    permalink: /profiles/:path/

# Build settings
markdown: kramdown