# Site settings
title: Cloud2
email: getmore@cloud2.co.uk
description: > # this means to ignore newlines until "baseurl:"
  A cool white label website by Reg Tait built with Jekyll and using Dan Eden's Toast grid layout
baseurl: ""
url: "https://example.com"
phone: "07800 100100"
twitter_id: Cloud2Ltd
theme-path: theme-assets # path to header assets etc
map-api-key: AIzaSyB3U7uwIvCyq01orxppAIC1v73y-FBGygY
sass:
  sass_dir: _sass
  style: compressed

collections:
  solution:
    output: true
    permalink: /solution/:path/
  case:
    output: true
    permalink: /case-studies/:path/
  event-item:
    output: true
    permalink: /launch/:path/
  resource:
    output: true
    permalink: /resources/:path/
  partner:
    output: true
    permalink: /partners/:path/
  profile:
    output: true
    permalink: /profiles/:path/

# Build settings
markdown: kramdown